name: Build and Deploy JSONResume
on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - resume/**

permissions:
  id-token: write
  contents: read 

jobs:
  build:
    defaults:
      run:
        working-directory: resume
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-central-1
      AWS_ACCOUNT_ID: 673449159430
      AWS_BUCKET_NAME: dimitrios.dentsas.com
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Export resume as HTML
        uses: kelvintaywl/action-jsonresume-export@v1
        with:
          theme: caffeine
          resume_filepath: ./resume/resume.json
          output_filepath: ./resume/build/index.html
      - name: Authenticate to AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/dentsas_portfolio_page_iam_main
          aws-region: ${{ env.AWS_REGION }}
      - name: Copy resume to S3 bucket
        working-directory: resume 
        run: |
          aws s3 cp ./build/index.html s3://${{ env.AWS_BUCKET_NAME }}/resume/index.html --acl public-read